# Generated by Django 5.2.1 on 2025-07-20 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_prdouctgallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrdouctGallery',
            new_name='ProductGallery',
        ),
    ]
