# Generated by Django 5.2.4 on 2025-07-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_rename_prdouctgallery_productgallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productgallery",
            options={
                "verbose_name": "productgallery",
                "verbose_name_plural": "Product Gallery",
            },
        ),
    ]
